### ISSUE TITLE
Anyway to use the SDK but use code from git head?

### ISSUE THREAD

**Issue by teotigraphix** [BowlerHatLLC/feathers-sdk#35]
I think I am running into some bugs you have already fixed but it doesn't look like there is a way to update the sdk other then checking it out and building it right?

**Comment by joshtynjala** [comment]
You may be able to rebuild feathers.swc and drop it into frameworks/libs. You would check out the mxml branch of BowlerHatLLC/feathers and build the source using your existing SDK. The master branch won't work because it doesn't have things like [Bindable].

Let me get the mxml branch updated, though. master hasn't been merged in since the alpha build.

**Comment by teotigraphix** [comment]
If you get this updated, could you just leave a little step by step of what I actually need to build? The targets or whatever, I haven't done this with this library.

**Comment by joshtynjala** [comment]
I merged in the latest changes. I think this should be all you need to do:
1. Check out the [BowlerHatLLC/feathers](https://github.com/BowlerHatLLC/feathers) repo
2. `git checkout mxml` to switch to the branch used by the Feathers SDK.
3. `compc --source-path+=source --include-sources+=source --output=feathers.swc`
4. Copy the SWC file to frameworks/libs in your Feathers SDK.

Use `compc` from your existing Feathers SDK 3.0.0-alpha. It should automatically use its own starling.swc as a dependency. This will be 2.0 beta, but I don't think anything has broken since then. If I'm wrong, then Starling needs to be rebuilt too.

I also updated the submodules in the Feathers SDK, so if you prefer, you can [build the SDK from source](http://feathersui.com/help/sdk/build-source-code.html).
