### ISSUE TITLE
Extending StarlingBootstrap

### ISSUE THREAD

**Issue by mphkz** [BowlerHatLLC/feathers-sdk#43]
Hi Josh,

This issue is related to a starling forum post: http://forum.starling-framework.org/topic/remoteobject-amf-for-feathers?replies=13#post-100337

The problem is that mx.messaging.config.LoaderConfig is a [Mixin] class, and on the method initializeMixins, is called the **init(null);** that triggers an error on that method of LoaderConfig.

I've tried to extend the StarlingBootstrap and override the method initializeMixins to avoid this particular case, but I get error on "public function info():Object":

`
Error: Method needs to be implemented in subclass
`

What do I need to do, so the compiler override this on my extended bootstrap?

Kind regards

**Comment by teotigraphix** [comment]
This is what I use;

```
    override public function info():Object
    {
        if (!_info)
        {
            var main:String = getQualifiedClassName(_mainClass);
            var theme:String = getQualifiedClassName(_themeClass);
            main = main.split(":").pop();
            theme = theme.split("::").join(".");
            _info = {
                    rootClassName:main,
                    themeClassName:theme
                };
        }
        
        return _info;
    }
```

So it seems, you need to just add your extra info in the object to return.

**Comment by devlfm** [comment]
Hi Michael,

Thank you for your reply. I've done that, and I can make RemoteObject
requests now, but the *override protected function initializeMixins():void*,
have empty info()["mixins"]. I think this variable is populated by the
compiler..

The app is working, but I don't know when will crash, or if will crash due
to this..

Thank you

2016-12-20 12:08 GMT+00:00 Michael Schmalle <notifications@github.com>:

**Comment by joshtynjala** [comment]
When you subclass StarlingBootstrap, and you add the [Frame] metadata to your main MXML class, you need to provide your own info() implementation. I think it's so that you can provide a custom bootstrap to [Frame] that isn't required to have an info() function. Pure ActionScript projects that don't use a framework would need something like that.

If the [Frame] metadata is in a class that the main MXML class subclasses, the compiler should generate info(). So, you should be able to create a simple class like this:

	package
	{
		import feathers.core.Application;

		[Frame(factoryClass="com.example.CustomBootstrap")]
		public class ApplicationWithCustomBootstrap extends Application
		{

		}
	}

Then, in your MXML, use your class as the root tag:

	<local:ApplicationWithCustomBootstrap xmlns:fx="http://ns.adobe.com/mxml/2009"
		xmlns:f="library://ns.feathersui.com/mxml"
		xmlns:local="*">

	</local:ApplicationWithCustomBootstrap>

I think this will generate info() for you.

**Comment by mphkz** [comment]
This is awesome!

Thank you Josh
