### ISSUE TITLE
LayoutGroup touchable

### ISSUE THREAD

**Issue by mphkz** [BowlerHatLLC/feathers-sdk#45]
Hi Josh,

Do you think its possible to add some method to recursive on all children set this property? Like the enabled or mouseChildren on Flex. Or is this related to the way Starling handles the children/parent properties?

Thank you

**Comment by joshtynjala** [comment]
Feathers components have an [isEnabled](https://feathersui.com/api-reference/feathers/core/FeathersControl.html#isEnabled) property that is similar to Flex's enabled property.

DisplayObjectContainer in Starling (and all Feathers components) have a [touchGroup](http://doc.starling-framework.org/current/starling/display/DisplayObjectContainer.html#touchGroup) property that works similarly to mouseChildren on Flash display objects.

**Comment by mphkz** [comment]
Hi Josh,

I tried touchGroup, I've set to false and worked, but when I set to true again doesn't work anymore.. maybe is starling issue.

I'm currently trying one skin from marphies and it haves a ripple effect on the button, but if I start to scroll over some button, the ripple is triggerer anyway and I want to avoid that.

When the panel is scrolling, the ripple don't start, and that's the expected behavior also when a scroll is about to start.

I don't know the best way to solve this.. I think that if I detect the touchGroup=false, and some ripple is playing I can inside the component cancel the ripple.

**Comment by joshtynjala** [comment]
If TouchPhase.BEGAN happens with a button as the target, you should probably stop the container from scrolling on TouchPhase.MOVED. Otherwise, it can become confusing for the user. You'll find that native mobile apps behave will stop a container from scrolling if you touch another component like a button or a toggle switch that should be interactive. I've observed this behavior on both Android and iOS.

If a touch begins on a button or another component that should be interactive, you can call stopScrolling() on the container to stop it from scrolling. If I remember correctly, you may need to wait to call stopScrolling() in a listener for FeathersEventType.SCROLL_START.

**Comment by mphkz** [comment]
Well, the issue is really on the "long press", what I feel from other android apps (and if feels right), is that there is a delay before trigger the "tap/over" event, so if you start scrolling will not trigger that "tap/over". If you release inside the button/area then dispatch the triggered event.

**Comment by joshtynjala** [comment]
Feathers has a delay before changing to the hover state in list item renderers, like you describe. It can be done internally, but you wouldn't be able to make a button do that without subclassing it.
