### ISSUE TITLE
Which .swc for IMXMLObject in pure ActionScript projects?

### ISSUE THREAD

**Issue by chrisvelevitch** [BowlerHatLLC/feathers-sdk#53]
In the pure ActionScript examples `Tabs` (the web version) that come with 3.5.0, I get compile errors:-
```
/Users/chris/libs/feathersSDK/v350-air310/frameworks/libs/feathers.swc
    Error:[Tabs]: (feathers.controls:TabNavigatorItem) Error code: 1046: Type was not found or was not a compile-time constant: [mx.core]::IMXMLObject.
    Error:[Tabs]: (feathers.controls:StackScreenNavigatorItem) Error code: 1046: Type was not found or was not a compile-time constant: [mx.core]::IMXMLObject.
```
Which `.swc` file contains this class? It's not in `mx.swc` nor `core.swc`.

**Comment by joshtynjala** [comment]
I have tranferred this issue to BowlerHatLLC/feathers-sdk, since it is more appropriate to be added there.

**Comment by joshtynjala** [comment]
Based on where it exists in the repository, it appears that `IMXMLObject` is compiled into *framework.swc*.

**Comment by joshtynjala** [comment]
You shouldn't run into this issue if you use the Tabs example that comes with the Feathers SDK instead. Since the sole purpose of the Feathers SDK is to add support for MXML, I'm not really sure why you're trying to use the pure ActionScript examples at all, to be honest.

If you're not interested in using MXML, then I recommend using the Adobe AIR SDK or the Apache Flex SDK and adding the Starling and Feathers UI libraries to your projects.
