### ISSUE TITLE
Attribute theme not allowed on Application tag

### ISSUE THREAD

**Issue by harry248** [BowlerHatLLC/feathers-sdk#9]
Using Intellij and following the tutorial I still get an "Attribute theme is not allowed here" when trying to set it on the Application tag.

**Comment by flexsurfer** [comment]
Will be fixed later, see http://feathersui.com/help/sdk/intellij-idea.html - on the bottom - Known Issues
In an MXML file that is based on <f:Application>, the editor will highlight the theme property in red, as if it doesn't exist. However, the compiler will compile this file without issues. This is not an error, and it may be ignored. This issue will be fixed in a future version of the Feathers SDK.
